config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :contacts
  get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :users do
    get :favorites, on: :collection 
  end
  root to: "feeds#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
  end

app/models/user.rb
class User < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                      before_validation { email.downcase! }
                      has_secure_password
                      validates :password, length: { minimum: 6 }
                      has_many :blogs
                      has_many :feeds
                      mount_uploader :image, ImageUploader
                      has_many :favorites, dependent: :destroy
                      
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
  
    private
  
    def login_required
      redirect_to new_session_path unless current_user
    end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

    def create
      favorite = current_user.favorites.create(feed_id: params[:feed_id])
      redirect_to feeds_path, notice: "you added #{favorite.feed.user.name}'s post to your favorites"
    end
  
    def destroy
      favorite = current_user.favorites.find_by(id: params[:id]).destroy
      redirect_to feeds_path, notice: "you have unfavorited #{favorite.feed.user.name}'s post"
    end
  end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    @feed = Feed.new
  end
  
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def edit
  end

  def create
    @feed = current_user.feeds.build(feed_params)
    if params[:back]
      render :new
    else
      if @feed.save
        ContactMailer.contact_mail(@feed).deliver
        redirect_to feeds_path, notice: "Feed was successfully created."
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feed_url(@feed), notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:image, :image_cache,:user_id, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'Login failed'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logged out'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
    
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to user_path(@user.id)
      else
        render :new
      end
    end

      def edit
        @user = User.find(params[:id])
      end
    
      def show
        @user = User.find(params[:id])
        @feeds = @user.feeds

        favorites = Favorite.where(user_id: current_user.id).pluck(:feed_id)
        @favorite_list = Feed.find(favorites)
      end

      def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to user_path(@user.id)
        else
          render :new
        end
      end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お気に入り一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Content</th>
      <th scope="col">User</th>
    </tr>
  </thead>

  <tbody>
    <% if @favorites.nil? %>
      <p> You have no favorites </p>
    <% else %>
      <% @favorites.each do |favorite| %>
        <tr>
          <td><%= image_tag favorite.feed.image.url %></td>
          <td><%= favorite.feed.content %></td>
          <td><%= favorite.feed.user.name %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/feeds/_form.html.erb
<%= form_with(model: feed) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

<div class="field">
  <%= form.label :content %>
  <%= form.text_area :content %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h2>投稿一覧</h2>
<%= link_to 'New Feed', new_feed_path %>
<hr />
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= feed.content %></td>
        <td><%= feed.user.name %></td>
        <td><%= link_to 'Show', feed %></td>
        <% if feed.user.name == current_user.name %>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif current_user.favorites.find_by(feed_id: feed.id).present? %>
        <td><%= link_to 'Unfavorite', favorite_path(id: current_user.favorites.find_by(feed_id: feed.id).id), method: :delete %></td>
      <% else %>
        <td><%= link_to 'Favorite', favorites_path(feed_id: feed.id), method: :post %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feed.user.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @feed.content %>
</p>
<br>
<br>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-sm bg-light mb-4">
        <h3 class="navbar-brand">Photogram</h3>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <% if logged_in? %>
          <li class="nav-link"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li class="nav-link"><%= link_to "Feed", feeds_path %></li>
          <li class="nav-link"><%= link_to "Favorites", favorites_path %></li>|
          <li class="nav-link"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
      </nav>
    </header>
    <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
  <footer class="bg-dark text-center text-white fixed-bottom">
    <h3>Photogram</h3>
  </footer>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
    </div>
    <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email %>
    </div>
    <div class="field">
    <%= form.label :password %>
    <%= form.text_area :password %>
    </div>
    </div>
    <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_area :password_confirmation %>
    </div>
    <div class="edit">
    <%= form.label :image %>
    <%= form.file_field :image %>
    </div>
<br>
  <div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
<br>
<br>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h2>My page</h2>
<%= link_to '編集', edit_user_path(@user) %> 
<hr />
<p>
  <strong>User</strong><br>
  <%= @user.name %>
</p>
<p>
  <strong>Profile photo:</strong><br>
  <% if not @user.image.url.nil? %>
    <%= image_tag @user.image.url, class:'icon' %>
  <% else %>
    未登録
  <% end %>
</p>
<p>
  <strong>e-mail:</strong><br> 
  <%= @user.email %>
  </p>